spring:
  datasource:
    url: ${LIB_DB} #데이터베이스 연결 URL
    username: ${LIB_DB_USERNAME}
    password: ${LIB_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver # 데이터베이스 연결에 사용될 JDBC 드라이버의 클래스 이름
  jpa:
    hibernate:
      ddl-auto: none #Hibernate의 데이터베이스 스키마 자동 생성 전략. validate 는  애플리케이션 실행 시 데이터베이스 스키마가 엔티티와 정확히 일치하는지 검증
    database-platform: org.hibernate.dialect.MySQL5Dialect #사용할 SQL 방언(Dialect)을 지정
    show-sql: true
    properties:
      hibernate:
        format_sql: true #Hibernate가 출력하는 SQL 을 보기 좋게 포맷팅
config:
  domain: {} #사용자 정의 설정
